export const jwtConstants = {
  secret:
    'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};

export const PUBLIC_KEY = 'SDFGHJHGRFEERTEWRTFVNBXVZ';

export const PERMISO_KEY =
  'SDFGHJHGRFEERTEWRTFVNBXVFGRTHYRHERWRQEWQgghjfhdgrsfdZ';

export const PUBLIC_INTERNO_KEY =
  'SDFGHJHGRFEERTEWRTFVNBXVFGRTHYRHERWRQEWQgghjfhdgrwrtewqwrwq4rtfesfdZ';
