export enum PermisosE {
  GASTO_LISTAR = 'LISTAR_GASTO',
  GASTO_CREAR = 'CREAR_GASTO',
  GASTO_EDITAR = 'EDITAR_GASTO',
  GASTO_ELIMINAR = 'ELIMINAR_GASTO',

  LECTURA_CREAR = 'CREAR_LECTURA',
  LECTURA_LISTAR = 'LISTAR_LECTURA',
  LECTURA_EDITAR = 'EDITAR_LECTURA',

  PAGO_LISTAR = 'LISTAR_PAGO',
  PAGO_CREAR = 'CREAR_PAGO',
  PAGO_ANULAR = 'ANULAR_PAGO',

  TARIFA_LISTAR = 'LISTAR_TARIFA',
  TARIFA_EDITAR = 'EDITAR_TARIFA',
  TARIFA_CREAR = 'CREAR_TARIFA',
  TARIFA_ELIMINAR = 'ELIMINAR_TARIFA',

  MEDIDOR_LISTAR = 'LISTAR_MEDIDOR',
  MEDIDOR_EDITAR = 'EDITAR_MEDIDOR',
  MEDIDOR_CREAR = 'CREAR_MEDIDOR',
  MEDIDOR_ELIMINAR = 'ELIMINAR_MEDIDOR',

  ROL_LISTAR = 'LISTAR_ROL',
  ROL_EDITAR = 'EDITAR_ROL',
  ROL_CREAR = 'CREAR_ROL',
  ROL_ELIMINAR = 'ELIMINAR_ROL',
}
